version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Port pour les clients AMQP
      - "15672:15672" # Port pour l'interface web de management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}

  # ms-admin:
  #   container_name: admin
  #   build:
  #     context: ./services/admin
  #     dockerfile: Dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - rabbitmq
  #   networks:
  #     - mynetwork

volumes:
  rabbitmq_data:

networks:
  mynetwork:
    driver: bridge
