version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672" # Port pour les clients AMQP
      - "15672:15672" # Port pour l'interface web de management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    networks:
      - ms_admin_network
      - ms_user_network
  
  # gateway:
  #   container_name: gateway
  #   build:
  #     context: ./services/gateway
  #     dockerfile: Dockerfile
  #   ports:
  #     - 80:80
  #   networks:
  #     - ms_admin_network
  #     - ms_user_network

  ms-admin:
    container_name: admin
    image: gregcesimaalsi23/goodfood-admin:latest
    # build:
    #   context: ./services/admin
    #   dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - ms_admin_network

  ms-user:
    container_name: user
    image: gregcesimaalsi23/goodfood-user-management:latest
    # build:
    #   context: ./services/user-management
    #   dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    depends_on:
      - rabbitmq
    networks:
      - ms_user_network

volumes:
  rabbitmq_data:

networks:
  ms_admin_network:
    driver: bridge
  ms_user_network:
    driver: bridge