apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: goodfood
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: ms-product-database
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: products

        - name: ms-product
          image: gregcesimaalsi23/goodfood-products:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: goodfood
spec:
  type: LoadBalancer
  selector:
    app: product
  ports:
    - name: "http"
      port: 80
      targetPort: 8080