services:
  database:
    container_name: "order-database"
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "127.0.0.1:1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    volumes:
      - "order-database:/var/lib/postgresql/data"

volumes:
  order-database: