buildamd:
	docker build --platform linux/amd64 -t gregcesimaalsi23/goodfood-order:amd64 .

pushamd:
	docker push gregcesimaalsi23/goodfood-order:amd64

builarm:
	docker build --plaform linux/arm64 -t gregcesimaalsi23/goodfood-order:arm64 .

pusharm:
	docker push gregcesimaalsi23/goodfood-order:arm64