apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-deployment
  namespace: goodfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
        - name: user-management
          image: gregcesimaalsi23/goodfood-user-management:latest
          ports:
            - containerPort: 3000
          env:
            - name: RABBITMQ_URL
              value: amqp://user:password@rabbitmq:5672
