services:
  setup-database:
    image: kong/kong-gateway:3.7.1.2
    networks:
      - kong-net
    env_file:
      - env.docker
    depends_on:
      - database
    command: "kong migrations bootstrap"

  database:
    container_name: kong-database
    image: postgres:13
    ports:
      - 5432:5432
    networks:
      - kong-net
    env_file:
      - env.docker

  gateway:
    container_name: kong-gateway
    image: kong/kong-gateway:3.7.1.2
    networks:
      - kong-net
    env_file:
      - env.docker
    depends_on:
      - database
    ports:
      - 8000:8000 
      - 8443:8443 
      - 8001:8001 
      - 8444:8444 
      - 8002:8002 
      - 8445:8445 
      - 8003:8003 
      - 8004:8004

networks:
  kong-net: