apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: goodfood
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: user
            - name: RABBITMQ_DEFAULT_PASS
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: goodfood
spec:
  type: NodePort
  ports:
    - name: "webadmin"
      port: 15672
      targetPort: 15672
      nodePort: 30300
    - name: "amqp"
      port: 5672
      targetPort: 5672
  selector:
    app: rabbitmq
