services:
  database:
    container_name: user-database
    image: mcr.microsoft.com/mssql/server:2022-latest
    volumes:
      - ./user-data:/var/lib/postgresql/data
    environment:
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    hostname: mssql-srv