apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: goodfood
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: ms-order
          image: gregcesimaalsi23/goodfood-order:amd64
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: RABBITMQ_URL
              value: "amqp://user:password@rabbitmq-service:5672"
            - name: DATABASE_URL
              value: "sqlserver://127.0.0.1:1433;database=orders;user=sa;password={yourStrongPassword#};trustServerCertificate=true;encrypt=true;"
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
        - name: database-order
          image: mcr.microsoft.com/mssql/server:2022-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_SA_PASSWORD
              value: "yourStrongPassword#"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: goodfood
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - name: "http"
      port: 3000
      targetPort: 3000
      nodePort: 30001
