name: Build Docker Images for Admin Service

on:
  push:
    branches:
      - feat-github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./services/admin/Dockerfile
          push: true
          tags: gregcesimaalsi23/goodfood-admin:latest

    strategy:
      matrix:
        service: [admin, user-management]
