name: Build Docker Images

on: 
  push:
    branches:
      - feat-github-actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./services/${{ matrix.service }}/Dockerfile
        push: true
        tags: your-dockerhub-username/${{ matrix.service }}:latest

    strategy:
      matrix:
        service: [admin, user-management]
