name: Build and Push Docker image and Restart Service

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-repo-name:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"

      - name: Connect to Kubernetes cluster
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig.yaml
          kubectl config set-cluster your-cluster --server=${{ secrets.KUBE_SERVER }} --certificate-authority=kubeconfig.yaml
          kubectl config set-credentials github-action --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context default --cluster=your-cluster --user=github-action
          kubectl config use-context default

      - name: Restart Service
        run: kubectl rollout restart deployment your-deployment-name
